export const SET_USERNAME = 'SET_USERNAME';
export const SET_PLAYERS = 'SET_PLAYERS';

export const CHANGE_PLAYER_STATE = 'CHANGE_PLAYER_STATE';
export const UPDATE_PLAYER_STATUS = 'UPDATE_PLAYER_STATUS';

export const SET_ROOMS = 'SET_ROOMS';
export const UPDATE_ROOM_STATUS = 'UPDATE_ROOM_STATUS';
export const UPDATE_CURRENT_ROOM = 'UPDATE_CURRENT_ROOM';
